spring.application.name=Sathish

# this is for logging
logging.file.path=logs
#logging.file.name=${logging.file.path}/${spring.application.name}.log
#logging.logback.rollingpolicy.file-name-pattern=${logging.file.path}/${spring.application.name}-%d{yyyy-MM-dd}-%i.log
#logging.logback.rollingpolicy.max-file-size=1KB

# this is for Profile
spring.profiles.active=prod
